server:
  port: 8080
  servlet:
    context-path: /community

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456abc
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coding.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
logging:
  level:
    com.coding.community: debug
pagehelper:
  helperDialect：mysql